steps:
  - name: "ubuntu"
    id: "test"
    entrypoint: "bash"
    args:
      - "-eEuo"
      - "pipefail"
      - "-c"
      - |-
        echo "$_HELLO"

substitutions:
  _HELLO: "sup"

options:
  substitutionOption: ALLOW_LOOSE
  logging: CLOUD_LOGGING_ONLY