apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: hammer
  annotations:
    team: "ghost-pack"
    description: "The hammer CLI."
spec:
  components:
    - name: hammer
      type: gocli
      # TODO: flesh out properties and traits and stuff eventually.
    - name: hammer-cicd
      type: cloudbuild
      properties:
        path: ./cloudbuild/cloudbuild.yaml
    - name: hammer-toolkit
      type: toolkit
      properties:
        path: ./wolfi-base.yaml
#      properties:
#        entrypoint: ./cmd/server
#      traits:
#        - type: resources
#          properties:
#            cpu: "1000m"
#            memory: 1Gi
#        - type: scalar
#          properties:
#            replicas: 2