apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: hammer-central
  annotations:
    team: "hammer-central"
    description: "The hammer CLI."
spec:
  components:
    - name: hammer
      type: gocli
    - name: hammer-cicd
      type: cloudbuild
      properties:
        path: ./cloudbuild/cloudbuild.yaml
        trigger_type: "webhook"
        service_account: "sa-oam@hammer-central-prod.iam.gserviceaccount.com"
        tests:
          - path: ./cloudbuild/cloudbuild_test.yaml
            required: true
    - name: hammer-toolkit
      type: toolkit
      properties:
        path: ./wolfi-base.yaml
    - name: hammer-opentofu
      type: opentofu
      properties:
        path: ./opentofu
  policies:
    - name: prod
      type: environment
      properties:
        environment: prod
        overrides:
          - component: hammer-cicd
            properties:
              service_account: "sa-oam@hammer-central-prod.iam.gserviceaccount.com"