apiVersion: platform.hammerplatform.dev/v1alpha1
kind: Tenant
metadata:
  name: hammer-central
  annotations:
    platform.hammerplatform.dev/platform-project: "true"
spec:
  billingAccount: "ABCDE-12345-FGHIJ"
  parentFolder: "937506553540"
  allowedAPIs:
    - cloudbuild.googleapis.com
    - artifactregistry.googleapis.com
    - storage.googleapis.com
    - secretmanager.googleapis.com
    - logging.googleapis.com
    - monitoring.googleapis.com
    - pubsub.googleapis.com
    - cloudtrace.googleapis.com
  environments:
    - prod                         # hammer-central only has one environment
  serviceAccounts:
    - name: sa-provisioner
      description: "Provisions GCP projects and resources for tenants"
      roles:
        project:
          - roles/storage.objectAdmin
        organization:
          - roles/resourcemanager.projectCreator
          - roles/resourcemanager.folderCreator
          - roles/orgpolicy.policyAdmin
          - roles/iam.serviceAccountAdmin
          - roles/serviceusage.serviceUsageAdmin
          - roles/billing.user
          - roles/resourcemanager.organizationAdmin
    - name: sa-oam
      description: "Runs CI/CD pipelines interpreting OAM files"
      roles:
        project:
          - roles/iam.serviceAccountTokenCreator
          - roles/artifactregistry.writer
          - roles/cloudbuild.builds.editor
          - roles/storage.objectAdmin
          - roles/pubsub.publisher
          - roles/pubsub.subscriber